export const defaultLight = {
  bg: "var(--color-white)",
  fg: "var(--color-gray-950)",
  primary: "var(--color-blue-600)",
  "primary-fg": "var(--color-white)",
  secondary: "var(--color-gray-100)",
  "secondary-fg": "var(--color-gray-950)",
  overlay: "var(--color-white)",
  "overlay-fg": "var(--color-gray-950)",
  accent: "var(--color-blue-600)",
  "accent-fg": "var(--color-white)",
  muted: "var(--color-gray-100)",
  "muted-fg": "var(--color-gray-600)",
  success: "var(--color-emerald-600)",
  "success-fg": "var(--color-white)",
  warning: "var(--color-amber-400)",
  "warning-fg": "var(--color-amber-950)",
  danger: "var(--color-red-600)",
  "danger-fg": "var(--color-red-50)",
  border: "var(--color-gray-200)",
  input: "var(--color-gray-300)",
  ring: "var(--color-blue-600)",
  navbar: "var(--color-gray-50)",
  "navbar-fg": "var(--color-gray-950)",
  sidebar: "var(--color-gray-50)",
  "sidebar-fg": "var(--color-gray-950)",
  "chart-1": "var(--color-blue-600)",
  "chart-2": "var(--color-blue-400)",
  "chart-3": "var(--color-blue-300)",
  "chart-4": "var(--color-blue-200)",
  "chart-5": "var(--color-blue-100)",
  "radius-lg": "0.5rem",
  "radius-xs": "calc(var(--radius-lg) * 0.5)",
  "radius-sm": "calc(var(--radius-lg) * 0.75)",
  "radius-md": "calc(var(--radius-lg) * 0.9)",
  "radius-xl": "calc(var(--radius-lg) * 1.25)",
  "radius-2xl": "calc(var(--radius-lg) * 1.5)",
  "radius-3xl": "calc(var(--radius-lg) * 2)",
  "radius-4xl": "calc(var(--radius-lg) * 3)",
}

export const defaultDark = {
  bg: "var(--color-gray-950)",
  fg: "var(--color-gray-50)",
  primary: "var(--color-blue-600)",
  "primary-fg": "var(--color-white)",
  secondary: "oklch(0.248 0.033 256.848)",
  "secondary-fg": "var(--color-gray-50)",
  accent: "var(--color-blue-600)",
  "accent-fg": "var(--color-white)",
  muted: "var(--color-gray-900)",
  "muted-fg": "var(--color-gray-400)",
  overlay: "oklch(0.170 0.034 264.665)",
  "overlay-fg": "var(--color-gray-50)",
  success: "var(--color-emerald-600)",
  "success-fg": "var(--color-white)",
  warning: "var(--color-amber-400)",
  "warning-fg": "var(--color-amber-950)",
  danger: "var(--color-red-600)",
  "danger-fg": "var(--color-red-50)",
  border: "oklch(0.273 0.034 259.733)",
  input: "oklch(0.293 0.034 259.733)",
  ring: "var(--color-blue-600)",
  navbar: "oklch(0.170 0.034 264.665)",
  "navbar-fg": "var(--color-gray-50)",
  sidebar: "oklch(0.160 0.034 264.665)",
  "sidebar-fg": "var(--color-gray-50)",
  "chart-1": "var(--color-blue-700)",
  "chart-2": "var(--color-blue-500)",
  "chart-3": "var(--color-blue-400)",
  "chart-4": "var(--color-blue-300)",
  "chart-5": "var(--color-blue-200)",
}
